### ISSUE TITLE
RSS readers only display the first paragraph of posts

### ISSUE THREAD

**Issue by dslittle22** [AlexanderEllis/blog#2]
Hi! I enjoy your blog a lot, but only the first paragraph of each post actually shows up in my RSS reader so I always need to leave the app and go to your website. I also tried a second RSS reader and still only see the first paragraph. 

Not sure if this is intentional or not, but I thought I’d mention it to you in case you weren’t aware of it!

**Comment by AlexanderEllis** [comment]
Oh no, totally not intentional — I'll double check my hugo config to see if I can figure out what's going on. Thanks so much for the heads up!

**Comment by AlexanderEllis** [comment]
OK I think I figured it out! Looks like the default `index.xml` ships with `<description>{{ .Summary | html }}</description>
`, so I updated that to be the full thing with `<description>{{ .Content | html }}</description>`. From a quick check on https://alexanderell.is/index.xml and https://codebeautify.org/rssviewer it looks like it's displaying the full post, so hopefully it should be all set!

Thanks again!
